#version: 2.1
#orbs:
  #codecov: codecov/codecov@3
#jobs:
#  build:
 #   working_directory: ~/code
 #   docker:
 #     - image: circleci/android:api-30
#    environment:
  #    JVM_OPTS: -Xmx3200m
   # steps:
  #    - checkout
 #     - restore_cache:
 #         key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  #    - run:
   #       name: chmod permissions
   #       command: chmod +x ./gradlew
    #  - run:
    #      name: Download Dependencies
   #       command: ./gradlew androidDependencies
  #    - run:
     #     name: Install dependencies, run tests, and collect coverage
   #       command: ./gradlew build
        
    #  - save_cache:
     #     paths:
   #         - ~/.gradle
     #     key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
   #   - store_artifacts:
  #        path: app/build/reports
  #        destination: reports
   #   - store_test_results:
   #       path: app/build/test-results
version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Install dependencies, run tests, and collect coverage
          command: ./gradlew build
      - codecov/upload

          
workflow:
  version: 2.1
  build-test:
    jobs:
      - build
